// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Refugio.DAL.DbContexts;

namespace Refugio.DAL.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20210421161626_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Refugio.DML.Estudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estudos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ffb016d-d7e5-4218-b3d4-6ecd7760943b"),
                            Categoria = "Desenvolvimento",
                            Descricao = "Building an API is one thing, but building a truly RESTful API is something different. In this course, you'll learn how to build one using ASP.NET Core 3.",
                            Tipo = "Curso",
                            Titulo = "Building a RESTful API with ASP.NET Core 3"
                        },
                        new
                        {
                            Id = new Guid("48b95ded-b551-4e2b-80e1-5262a33ae350"),
                            Categoria = "Desenvolvimento",
                            Descricao = "Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way.",
                            Tipo = "Livro",
                            Titulo = "Clean Code"
                        },
                        new
                        {
                            Id = new Guid("e7836278-3c02-436f-af31-d696bc51b930"),
                            Categoria = "Ficção",
                            Descricao = "Winter is coming. Such is the stern motto of House Stark, the northernmost of the fiefdoms that owe allegiance to King Robert Baratheon in far-off King’s Landing",
                            Tipo = "Livro",
                            Titulo = "A Game of Thrones"
                        },
                        new
                        {
                            Id = new Guid("e6453a2b-c224-4093-9f0b-ef53d2d39621"),
                            Categoria = "Ciencia",
                            Descricao = "O planeta Terra tem cerca de 4,5 bilhões de anos. Numa fração ínfima desse tempo, uma espécie entre incontáveis outras o dominou: nós, humanos. Somos os animais mais evoluídos e mais destrutivos que jamais viveram.",
                            Tipo = "Livro",
                            Titulo = "Sapiens"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
