// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Refugio.DAL.DbContexts;

namespace Refugio.WebApi.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20210106231810_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Refugio.WebApi.Entities.Estudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estudos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f9756a1-45bc-4e2f-aeb8-48a69e0b2288"),
                            Categoria = "Desenvolvimento",
                            Descricao = "Building an API is one thing, but building a truly RESTful API is something different. In this course, you'll learn how to build one using ASP.NET Core 3.",
                            Tipo = "Curso",
                            Titulo = "Building a RESTful API with ASP.NET Core 3"
                        },
                        new
                        {
                            Id = new Guid("db045230-1efb-4142-ac04-6a3a4d72a13e"),
                            Categoria = "Desenvolvimento",
                            Descricao = "Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way.",
                            Tipo = "Livro",
                            Titulo = "Clean Code"
                        },
                        new
                        {
                            Id = new Guid("12cebd5d-13d8-4bc1-93f7-e573349f5c47"),
                            Categoria = "Ficção",
                            Descricao = "Winter is coming. Such is the stern motto of House Stark, the northernmost of the fiefdoms that owe allegiance to King Robert Baratheon in far-off King’s Landing",
                            Tipo = "Livro",
                            Titulo = "A Game of Thrones"
                        },
                        new
                        {
                            Id = new Guid("a172d006-266a-4b4d-a69b-72bae674f802"),
                            Categoria = "Ciencia",
                            Descricao = "O planeta Terra tem cerca de 4,5 bilhões de anos. Numa fração ínfima desse tempo, uma espécie entre incontáveis outras o dominou: nós, humanos. Somos os animais mais evoluídos e mais destrutivos que jamais viveram.",
                            Tipo = "Livro",
                            Titulo = "Sapiens"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
